[package]
name = "onet-matrix"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
onet-chains = { path = "../chains" }
onet-config = { path = "../config" }
onet-errors = { path = "../errors" }
onet-report = { path = "../report" }

async-recursion = { workspace = true }
base64 = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
url = { workspace = true }
