[package]
name = "onet-pools"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
onet-records = { path = "../records" }

codec = { workspace = true }
serde = { workspace = true }
subxt = { workspace = true }
