[package]
name = "onet-errors"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
actix-web = { workspace = true }
mobc = { workspace = true }
mobc-redis = { workspace = true }
subxt = { workspace = true }
subxt-metadata = { workspace = true }
codec = { workspace = true }
